ALTER TABLE mpsuscripciones
ADD COLUMN IF NOT EXISTS cobrorechazado BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS motivorechazo VARCHAR(200) NULL,
ADD COLUMN IF NOT EXISTS proximoreintento TIMESTAMP NULL;
