<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>UnitOfWork</RootNamespace>
    <AssemblyName>CobrosRecurrentes.UnitOfWork</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Repositories\CobrosRecurrentes.Repositories.csproj" />
  </ItemGroup>

</Project>
